// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvWYIdmWQzpmnrFH2nImOp9gqmox9XsbE',
    appId: '1:957228652992:web:c3913f02f6d16851d45025',
    messagingSenderId: '957228652992',
    projectId: 'todo-93118',
    authDomain: 'todo-93118.firebaseapp.com',
    storageBucket: 'todo-93118.appspot.com',
    measurementId: 'G-9NZ9TTPPGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKB9CN3cv5PfMIm5gVQBpODClf0jlqUuI',
    appId: '1:957228652992:android:7969c36cc5fce439d45025',
    messagingSenderId: '957228652992',
    projectId: 'todo-93118',
    storageBucket: 'todo-93118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3WzDFkLj8Jtbbjb6L2O-4Fk7rcPAclRM',
    appId: '1:957228652992:ios:cac0c4ba8113160cd45025',
    messagingSenderId: '957228652992',
    projectId: 'todo-93118',
    storageBucket: 'todo-93118.appspot.com',
    iosClientId: '957228652992-ptfpsn17q951n1o5nnd5ta61lcpe26jb.apps.googleusercontent.com',
    iosBundleId: 'com.example.apiTranslator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3WzDFkLj8Jtbbjb6L2O-4Fk7rcPAclRM',
    appId: '1:957228652992:ios:eb26a9ff524bcab9d45025',
    messagingSenderId: '957228652992',
    projectId: 'todo-93118',
    storageBucket: 'todo-93118.appspot.com',
    iosClientId: '957228652992-sr0s6n6rpg8cjr7lh6tbpmi7nahst0pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.apiTranslator.RunnerTests',
  );
}
